"use client";

import { ChangeEvent, useState } from "react";
import { Plus, Save, Trash2, Upload } from "lucide-react";
import { type ArchivedEvent, type Contributor, type CoreMember, type SiteContent } from "@/lib/content-types";

const colors = ["acid", "paper", "red", "ink"] as const;

function newLead(): CoreMember { return { id: `lead-${Date.now()}`, name: "NEW CORE TEAM MEMBER", role: "ROLE", initials: "TH", bio: "", tags: ["COMMUNITY"], photo: "", color: "acid" }; }
function newPerson(): Contributor { return { id: `contributor-${Date.now()}`, name: "NEW CONTRIBUTOR", role: "VOLUNTEER", year: "2025", note: "", photo: "", color: "acid", eventIds: [] }; }
function newEvent(): ArchivedEvent { return { id: `event-${Date.now()}`, date: "MM.YY", title: "NEW EVENT", type: "EVENT", note: "", photo: "", color: "acid", contributorIds: [] }; }

export function AdminPanel({ initialContent }: { initialContent: SiteContent }) {
  const [content, setContent] = useState(initialContent);
  const [message, setMessage] = useState("READY TO EDIT");
  const [saving, setSaving] = useState(false);

  function updateLead(id: string, field: keyof CoreMember, value: string | string[]) { setContent((current) => ({ ...current, coreTeam: current.coreTeam.map((lead) => lead.id === id ? { ...lead, [field]: value } as CoreMember : lead) })); }
  function updatePerson(id: string, field: keyof Contributor, value: string | string[]) { setContent((current) => ({ ...current, contributors: current.contributors.map((person) => person.id === id ? { ...person, [field]: value } as Contributor : person) })); }
  function updateEvent(id: string, field: keyof ArchivedEvent, value: string | string[]) { setContent((current) => ({ ...current, events: current.events.map((event) => event.id === id ? { ...event, [field]: value } as ArchivedEvent : event) })); }
  function remove(section: "coreTeam" | "contributors" | "events", id: string) { setContent((current) => ({ ...current, [section]: current[section].filter((item) => item.id !== id) } as SiteContent)); }
  function toggleEventPerson(eventId: string, personId: string) { const event = content.events.find((item) => item.id === eventId); const person = content.contributors.find((item) => item.id === personId); if (!event || !person) return; const linked = event.contributorIds.includes(personId); updateEvent(eventId, "contributorIds", linked ? event.contributorIds.filter((id) => id !== personId) : [...event.contributorIds, personId]); updatePerson(personId, "eventIds", linked ? person.eventIds.filter((id) => id !== eventId) : [...person.eventIds, eventId]); }

  async function upload(file: File, section: "coreTeam" | "contributors" | "events", id: string) { setMessage("UPLOADING IMAGE..."); const form = new FormData(); form.set("file", file); const response = await fetch("/api/admin/upload", { method: "POST", body: form }); const result = await response.json().catch(() => ({ error: "Upload failed." })); if (!response.ok) { setMessage(result.error); return; } updateSectionPhoto(section, id, result.url); setMessage("IMAGE ADDED - SAVE TO PUBLISH"); }
  function updateSectionPhoto(section: "coreTeam" | "contributors" | "events", id: string, photo: string) { setContent((current) => ({ ...current, [section]: current[section].map((item) => item.id === id ? { ...item, photo } : item) } as SiteContent)); }
  function fileChange(file: File | undefined, section: "coreTeam" | "contributors" | "events", id: string) { if (file) void upload(file, section, id); }
  async function save() { setSaving(true); setMessage("SAVING..."); const response = await fetch("/api/admin/content", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(content) }); const result = await response.json().catch(() => ({ error: "Save failed." })); if (!response.ok) { setMessage(result.error); setSaving(false); return; } setContent(result); setMessage("PUBLISHED"); setSaving(false); }
  async function logout() { await fetch("/api/admin/logout", { method: "POST" }); window.location.reload(); }

  return <main className="admin-page">
    <header className="admin-topbar"><a href="/" className="brand"><i>TH</i><span>SCET<br />CHAPTER</span></a><div><span>{message}</span><button onClick={logout}>LOG OUT</button></div></header>
    <section className="admin-hero"><p>( TINKERHUB SCET / CONTENT DESK )</p><h1>KEEP THE<br /><i>SIGNAL</i> FRESH.</h1><button className="admin-save" onClick={save} disabled={saving}><Save size={16} /> {saving ? "SAVING" : "SAVE + PUBLISH"}</button></section>

    <section className="admin-section"><div className="admin-section-head"><div><p>( 01 / LEADERSHIP SLOTS )</p><h2>CORE<br />TEAM</h2></div><button onClick={() => setContent((current) => ({ ...current, coreTeam: [...current.coreTeam, newLead()] }))}><Plus size={16} /> ADD LEAD</button></div><div className="admin-editor-grid">{content.coreTeam.map((lead) => <article className={`admin-card admin-card--${lead.color}`} key={lead.id}><div className="admin-card-top"><span>{lead.role}</span><button aria-label={`Remove ${lead.name}`} onClick={() => remove("coreTeam", lead.id)}><Trash2 size={16} /></button></div><div className="admin-photo">{lead.photo ? <img src={lead.photo} alt="" /> : <span>LEAD PHOTO</span>}<label><Upload size={15} /><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event: ChangeEvent<HTMLInputElement>) => fileChange(event.target.files?.[0], "coreTeam", lead.id)} /></label></div><label>DISPLAY NAME<input value={lead.name} onChange={(event) => updateLead(lead.id, "name", event.target.value)} /></label><div className="admin-two-col"><label>ROLE<input value={lead.role} onChange={(event) => updateLead(lead.id, "role", event.target.value)} /></label><label>INITIALS<input value={lead.initials} onChange={(event) => updateLead(lead.id, "initials", event.target.value)} /></label></div><label>SHORT BIO<textarea value={lead.bio} onChange={(event) => updateLead(lead.id, "bio", event.target.value)} /></label><label>COLOUR<select value={lead.color} onChange={(event) => updateLead(lead.id, "color", event.target.value)}>{colors.map((color) => <option key={color}>{color}</option>)}</select></label></article>)}</div></section>

    <section className="admin-section"><div className="admin-section-head"><div><p>( 02 / PEOPLE ARCHIVE )</p><h2>VOLUNTEERS<br />+ HOSTS</h2></div><button onClick={() => setContent((current) => ({ ...current, contributors: [...current.contributors, newPerson()] }))}><Plus size={16} /> ADD PERSON</button></div><div className="admin-editor-grid">{content.contributors.map((person) => <article className={`admin-card admin-card--${person.color}`} key={person.id}><div className="admin-card-top"><span>{person.role}</span><button aria-label={`Remove ${person.name}`} onClick={() => remove("contributors", person.id)}><Trash2 size={16} /></button></div><div className="admin-photo">{person.photo ? <img src={person.photo} alt="" /> : <span>PERSON PHOTO</span>}<label><Upload size={15} /><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event: ChangeEvent<HTMLInputElement>) => fileChange(event.target.files?.[0], "contributors", person.id)} /></label></div><label>NAME<input value={person.name} onChange={(event) => updatePerson(person.id, "name", event.target.value)} /></label><div className="admin-two-col"><label>ROLE<select value={person.role} onChange={(event) => updatePerson(person.id, "role", event.target.value)}><option>VOLUNTEER</option><option>HOST</option><option>VOLUNTEER + HOST</option></select></label><label>YEAR<input value={person.year} onChange={(event) => updatePerson(person.id, "year", event.target.value)} /></label></div><label>SHORT NOTE<textarea value={person.note} onChange={(event) => updatePerson(person.id, "note", event.target.value)} /></label><div className="admin-link-summary">LINKED EVENTS <b>{person.eventIds.length}</b></div></article>)}</div></section>

    <section className="admin-section admin-events-section"><div className="admin-section-head"><div><p>( 03 / EVENT ARCHIVE )</p><h2>PAST<br />EVENTS</h2></div><button onClick={() => setContent((current) => ({ ...current, events: [...current.events, newEvent()] }))}><Plus size={16} /> ADD EVENT</button></div><div className="admin-editor-grid">{content.events.map((event) => <article className={`admin-card admin-card--${event.color}`} key={event.id}><div className="admin-card-top"><span>{event.type}</span><button aria-label={`Remove ${event.title}`} onClick={() => remove("events", event.id)}><Trash2 size={16} /></button></div><div className="admin-photo">{event.photo ? <img src={event.photo} alt="" /> : <span>EVENT PHOTO</span>}<label><Upload size={15} /><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(eventChange) => fileChange(eventChange.target.files?.[0], "events", event.id)} /></label></div><label>TITLE<input value={event.title} onChange={(eventChange) => updateEvent(event.id, "title", eventChange.target.value)} /></label><div className="admin-two-col"><label>DATE<input value={event.date} onChange={(eventChange) => updateEvent(event.id, "date", eventChange.target.value)} /></label><label>TYPE<input value={event.type} onChange={(eventChange) => updateEvent(event.id, "type", eventChange.target.value)} /></label></div><label>ARCHIVE NOTE<textarea value={event.note} onChange={(eventChange) => updateEvent(event.id, "note", eventChange.target.value)} /></label><label>COLOUR<select value={event.color} onChange={(eventChange) => updateEvent(event.id, "color", eventChange.target.value)}>{colors.map((color) => <option key={color}>{color}</option>)}</select></label><div className="admin-link-editor"><span>WHO WAS THERE?</span>{content.contributors.length === 0 && <small>Add people above first.</small>}{content.contributors.map((person) => <label key={person.id}><input type="checkbox" checked={event.contributorIds.includes(person.id)} onChange={() => toggleEventPerson(event.id, person.id)} />{person.name}</label>)}</div></article>)}</div></section>
    <button className="admin-floating-save" onClick={save} disabled={saving}>{saving ? "SAVING" : "SAVE"}</button>
  </main>;
}
